name: Hello workflow

on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello to user
        run: echo "Hello User"