name: Python lint

on:
  push:
    branches: [main]


jobs:
  validate:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10","3.11","3.12"]
            
    steps:
      - name: checkout code
        uses: actions/checkout@v4

        
      - name: steps python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with: 
              python-version: "3.13"

      - name: Install dependencies
        run: pip install -r Matrix/requirements.txt

      - name: Run linter
        run: flake8 Matrix/app.py
